#!/usr/bin/env bash
# install.sh — one-shot installer for local-mc on Linux / macOS
#
# Usage:
#   cd /path/to/local-mc
#   bash scripts/install.sh
#
# What it does:
#   1. Checks Python 3.10+.
#   2. Creates a venv at ~/.local/lmc-venv.
#   3. pip-installs local-mc from the repo root.
#   4. Drops a thin lmc shim at ~/.local/bin/lmc.
#   5. Prints next-step instructions.
#
# To reinstall cleanly:
#   REINSTALL=1 bash scripts/install.sh

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
YELLOW='\033[1;33m'; RESET='\033[0m'

step()  { printf "${CYAN}  >> %s${RESET}\n" "$*"; }
ok()    { printf "${GREEN}  OK %s${RESET}\n" "$*"; }
warn()  { printf "${YELLOW}WARN %s${RESET}\n" "$*"; }
fail()  { printf "${RED}FAIL %s${RESET}\n" "$*"; exit 1; }

# ── locate Python 3.10+ ───────────────────────────────────────────────────────
step "Locating Python 3.10+..."

PYTHON=""
for candidate in python3 python python3.12 python3.11 python3.10; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        major=$(echo "$ver" | cut -d. -f1)
        minor=$(echo "$ver" | cut -d. -f2)
        if [ "$major" -gt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -ge 10 ]; }; then
            PYTHON="$candidate"
            ok "Found Python $ver at '$candidate'"
            break
        fi
    fi
done

[ -n "$PYTHON" ] || fail "Python 3.10+ not found. Install via your package manager or https://python.org"

# ── set up venv ───────────────────────────────────────────────────────────────
VENV_DIR="${HOME}/.local/lmc-venv"
BIN_DIR="${HOME}/.local/bin"

if [ "${REINSTALL:-0}" = "1" ] && [ -d "$VENV_DIR" ]; then
    step "Removing existing venv at $VENV_DIR..."
    rm -rf "$VENV_DIR"
    ok "Removed."
fi

if [ ! -d "$VENV_DIR" ]; then
    step "Creating venv at $VENV_DIR..."
    "$PYTHON" -m venv "$VENV_DIR"
    ok "Venv created."
else
    ok "Venv already exists at $VENV_DIR  (set REINSTALL=1 to rebuild)"
fi

PIP="$VENV_DIR/bin/pip"
PYTHON_VENV="$VENV_DIR/bin/python"

[ -x "$PIP" ] || fail "pip not found inside venv at $PIP"

# ── locate repo root ──────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

[ -f "$REPO_ROOT/pyproject.toml" ] || \
    fail "pyproject.toml not found in $REPO_ROOT — run this script from inside the repo."

# ── install ───────────────────────────────────────────────────────────────────
step "Upgrading pip..."
"$PIP" install --upgrade --quiet pip

step "Installing local-mc from $REPO_ROOT..."
"$PIP" install --quiet "$REPO_ROOT"
ok "local-mc installed."

# ── write shim ────────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
SHIM="$BIN_DIR/lmc"

cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# lmc shim — generated by scripts/install.sh
exec "$PYTHON_VENV" -m lmc.cli "\$@"
EOF
chmod +x "$SHIM"
ok "Shim written to $SHIM"

# ── PATH advisory ─────────────────────────────────────────────────────────────
if ! echo "$PATH" | tr ':' '\n' | grep -qxF "$BIN_DIR"; then
    warn "$BIN_DIR is not on your PATH."
    echo ""
    echo "  Add it permanently by appending this to ~/.bashrc or ~/.zshrc:"
    echo ""
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
fi

# ── smoke test ────────────────────────────────────────────────────────────────
step "Verifying installation..."
if "$SHIM" --help &>/dev/null; then
    ok "lmc --help succeeded."
else
    warn "lmc --help exited non-zero — PATH update may be needed."
fi

# ── next steps ────────────────────────────────────────────────────────────────
echo ""
printf "${GREEN}  local-mc installed.${RESET}\n"
echo ""
echo "  Next steps:"
echo "    lmc init"
echo "    lmc add myproject /path/to/project"
echo "    lmc serve"
echo ""
echo "  Data lives at:"
echo "    Config : ~/.config/lmc/"
echo "    History: ~/.local/share/lmc/"
echo ""
